#!/usr/bin/env python3
import os
import re
import sys
from pathlib import Path
from shlex import quote
from typing import Tuple

from praktika.info import Info
from praktika.utils import Shell

from ci.praktika import Secret
from ci.praktika.gh import GH

# Section name constants used in PR templates
SECTION_DESCRIPTION = "LLM-generated Change Description"
SECTION_CHANGELOG = "LLM-generated Changelog Entry"


class CIAgent:

    def __init__(self):
        self.info = Info()

    def is_ready(self):
        if not self.ensure_claude_auth():
            return False
        if not self.ensure_claude_code_cli():
            return False
        return True

    def extract_autogenerated_content(self, filename: str) -> str:
        """LLM responses are written to .txt file by subagent and read back by this function"""
        try:
            with open(filename, "r", encoding="utf-8", errors="replace") as f:
                file_content = f.read()

            # Remove "EOF < /dev/null" if it exists
            file_content = file_content.replace("EOF < /dev/null", "")

            # Check for API errors in the response
            if file_content.strip().startswith("API Error: "):
                raise RuntimeError(
                    f"Claude API Error detected in {filename}: {file_content.strip()}"
                )

            return file_content
        except FileNotFoundError:
            print(f"Warning: {filename} not found")
            return ""
        except Exception as e:
            print(f"Error reading {filename}: {e}")
            raise

    def ensure_claude_auth(self) -> bool:
        try:
            if not os.environ.get("CLAUDE_CODE_USE_BEDROCK"):
                print("CLAUDE_CODE_USE_BEDROCK not set")
                return False
            if not os.environ.get("AWS_REGION"):
                print("AWS_REGION not set")
                return False
            return True
        except Exception as e:
            print(f"Something went wrong with setup of Claude environment: {e}")
            return False

    def ensure_claude_code_cli(self) -> bool:
        try:
            Shell.run("node --version", verbose=True)
            exit_code = Shell.run("command -v claude", verbose=False)
            if exit_code == 0:
                claude_path = Shell.get_output("command -v claude").strip()
                print(f"claude-code CLI found at: {claude_path}")
                return True
            else:
                raise Exception("claude command not found")
        except:
            print("claude-code not found")
            return False

    def extract_content_and_format_flag(
        self, body: str, section_name: str
    ) -> Tuple[str, bool]:
        """
        PR body markers look like:

        <!--- LLM-generated Change Description enabled=false -->
        ... optional content ...
        <!--- LLM-generated Change Description END --->

        and

        <!--- LLM-generated Changelog Entry enabled=true -->
        ... optional content ...
        <!--- LLM-generated Changelog Entry END --->
        """

        # Begin tag with enabled and optional format_only flags
        begin_pattern = rf"<!---\s*{re.escape(section_name)}\s+enabled=(true|false)(?:\s+format_only=(true|false))?\s*-->"
        end_pattern = rf"<!---\s*{re.escape(section_name)}\s+END\s*-->"

        begin_match = re.search(begin_pattern, body, re.IGNORECASE)
        end_match = None
        if begin_match:
            # find the end marker that comes AFTER the begin marker and for the same section
            end_match = re.search(end_pattern, body[begin_match.end() :], re.IGNORECASE)

        if begin_match and end_match:
            # Extract content between tags
            start = begin_match.end()
            end = begin_match.end() + end_match.start()
            content = body[start:end].strip()

            # Format flag: read from format_only (group 2). Default to false if missing.
            format_only = False
            if begin_match.lastindex and begin_match.lastindex >= 2:
                grp = begin_match.group(2)
                if grp is not None:
                    format_only = grp.lower() == "true"

            return content, format_only
        return "", False

    def insert_content_between_tags(
        self, text: str, section_name: str, new_content: str
    ) -> str:
        """
        Replace the content between the new-style LLM markers in the PR body.

        Markers look like:
        <!--- LLM-generated Change Description enabled=false format_only=false -->
        ... content ...
        <!--- LLM-generated Change Description END --->
        """

        # Look for a begin tag with enabled/format_only attributes and a section-specific end tag
        begin_pattern = rf"<!---\s*{re.escape(section_name)}\s+enabled=(true|false)(?:\s+format_only=(true|false))?\s*-->"
        end_pattern = rf"<!---\s*{re.escape(section_name)}\s+END\s*-->"

        begin_match = re.search(begin_pattern, text, re.IGNORECASE)
        end_match = None
        if begin_match:
            end_match = re.search(end_pattern, text[begin_match.end() :], re.IGNORECASE)

        if begin_match and end_match:
            # Always write back enabled=false and format_only=false as requested
            new_begin_tag = f"<!--- {section_name} enabled=false format_only=false -->"

            # Replace everything from BEGIN tag to END tag
            before = text[: begin_match.start()]
            after = text[begin_match.end() + end_match.end() :]

            return f"{before}{new_begin_tag}\n{new_content}\n<!--- {section_name} END -->{after}"
        return text

    def generate_description(self, diff_file: str, human_description: str) -> str:
        try:
            prompt = f"Use the pr-description-generator agent to generate a PR description for this PR. Read the diff from file: {diff_file}"
            # Write prompt to file and pipe it to claude to avoid shell escaping issues
            with open("prompt_description.txt", "w", encoding="utf-8") as f:
                f.write(prompt)

            command = f"cat prompt_description.txt | claude --output-format text --allowedTools 'Bash,Read' --permission-mode acceptEdits -p 'Generate PR description' > pr_description.txt"
            Shell.check(command)
            description = self.extract_autogenerated_content("pr_description.txt")
            return description
        except RuntimeError as e:
            if "API Error: " in str(e):
                # Re-raise API errors so they can be caught by the main job
                raise
            print(f"Error running claude command: {e}")
            return f"Error generating PR description: {e}"
        except Exception as e:
            print(f"Error running claude command: {e}")
            return f"Error generating PR description: {e}"

    def generate_changelog_entry(
        self, diff_file: str, human_changelog_entry: str
    ) -> str:
        try:
            prompt = f"Use the pr-changelog-generator agent to generate a PR changelog entry for this PR. Read the diff from file: {diff_file}"
            # Write prompt to file and pipe it to claude to avoid shell escaping issues
            with open("prompt_changelog.txt", "w", encoding="utf-8") as f:
                f.write(prompt)

            command = f"cat prompt_changelog.txt | claude --output-format text --allowedTools 'Bash,Read' --permission-mode acceptEdits -p 'Generate changelog entry' > changelog_entry.txt"
            Shell.check(command)
            changelog = self.extract_autogenerated_content("changelog_entry.txt")
            return changelog
        except RuntimeError as e:
            if "API Error: " in str(e):
                # Re-raise API errors so they can be caught by the main job
                raise
            print(f"Error running claude command: {e}")
            return f"Error generating changelog entry: {e}"
        except Exception as e:
            print(f"Error running claude command: {e}")
            return f"Error generating changelog entry: {e}"

    def format_description_or_changelog(self, type: str, content: str):
        if type == "description":
            try:
                with open("user_pr_description.txt", "w", encoding="utf-8") as f:
                    f.write(content)
                prompt = f"Use the pr-description-formatter agent to read the user provided description stored in user_pr_description.txt and format it."

                # Write prompt to file and pipe it to claude to avoid shell escaping issues
                with open("prompt_user_description.txt", "w", encoding="utf-8") as f:
                    f.write(prompt)

                command = f"cat prompt_user_description.txt | claude --output-format text --allowedTools 'Bash,Read' --permission-mode acceptEdits -p 'format' > formatted_user_description.txt"
                Shell.check(command)
                changelog = self.extract_autogenerated_content(
                    "formatted_user_description.txt"
                )
                return changelog
            except Exception as e:
                print(f"Error running claude command: {e}")
                return f"Error formatting user description: {e}"

        elif type == "changelog":
            try:
                with open("user_changelog_entry.txt", "w", encoding="utf-8") as f:
                    f.write(content)
                prompt = f"Use the pr-changelog-formatter agent to read the user provided changelog entry stored in user_changelog_entry.txt and format it."

                # Write prompt to file and pipe it to claude to avoid shell escaping issues
                with open("prompt_user_changelog.txt", "w", encoding="utf-8") as f:
                    f.write(prompt)

                command = f"cat prompt_user_changelog.txt | claude --output-format text --allowedTools 'Bash,Read' --permission-mode acceptEdits -p 'format' > formatted_user_changelog.txt"
                Shell.check(command)
                changelog = self.extract_autogenerated_content(
                    "formatted_user_changelog.txt"
                )
                return changelog
            except Exception as e:
                print(f"Error running claude command: {e}")
                return f"Error formatting user description: {e}"
        else:
            raise Exception(
                "No valid type was provided. Please specify either 'description' or 'changelog'"
            )

    def update_pr_body_with_generated_content(
        self, pr_body: str, description: str, changelog_entry: str
    ) -> str:
        updated_body = pr_body
        updated_body = self.insert_content_between_tags(
            updated_body, SECTION_DESCRIPTION, description
        )
        updated_body = self.insert_content_between_tags(
            updated_body, SECTION_CHANGELOG, changelog_entry
        )

        return updated_body

    def should_process_section(
        self, section_name: str
    ) -> Tuple[bool, Tuple[bool, str]]:
        # Parse section content and format flag
        content, should_format = self.extract_content_and_format_flag(
            self.info.pr_body, section_name
        )

        # Determine if the section is enabled
        begin_pattern = rf"<!---\s*{re.escape(section_name)}\s+enabled=(true|false)(?:\s+format_only=(true|false))?\s*-->"
        begin_match = re.search(begin_pattern, self.info.pr_body, re.IGNORECASE)
        enabled = False
        if begin_match:
            enabled = begin_match.group(1).lower() == "true"

        """
        Processing happens if:
        - The section has enabled=true and there is no content between the begin and end markers -> LLM generates the content
        - The section has enabled=true, there is user-provided content, and the format_only flag is set to true -> LLM formats the content

        No processing occurs if:
        - enabled=false; or
        - there is user-provided content and the format_only flag is false
        """
        should_process = (enabled and (not content.strip())) or (
            should_format and bool(content.strip())
        )
        # Return shape: (should_format, content)
        return (should_process, (should_format, content))


if __name__ == "__main__":
    CIAgent = CIAgent()
    assert CIAgent.is_ready()
